baseURL: "https://www.sihaoli.com" 
title: Si Hao Li
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: About
          url: about/
          weight: 0
        - name: Publications
          url: articles/
          weight: 1
        - name: Talks
          url: talks/
          weight: 2
        - name: Teaching
          url: teaching/
          weight: 3 
        - name: Resume
          url: cv.pdf
        - name: Learning Ressources
          url: ressources/
          weight: 4
        - name: Past Positions
          url: past/
          weight: 5
        - name: Tutorials and Data
          url: publications/
          weight : 6

params:
    description: "PhD candidate in Economics at Telecom Paris (CREST). My research interests span Industrial Organization, Digital Economics, Economics of Innovation, and Computational Social Science. Contact: si.li@ip-paris.fr | si-hao.li@ensae.fr."
    author: Si Hao Li
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "02 Jan 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Si Hao Li
          subtitle: "PhD candidate in Economics at Telecom Paris (CREST). My research interests span Industrial Organization, Digital Economics, Economics of Innovation, and Computational Social Science.<br />Contact: si.li@ip-paris.fr | si-hao.li@ensae.fr."
          imageUrl: "photo3.png"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Si Hao Li
          buttons:
            - name: About
              url: about/
            - name: Publications
              url: articles/
            - name: Talks
              url: talks/
            - name: Teaching
              url: teaching/
            - name: Resume
              url: cv.pdf
            - name: Learning Ressources
              url: ressources/
            - name: Past Positions
              url: past/
            - name: Tutorials and Data
              url: publications/
    socialIcons:
        # - name: hal
        #   url: https://hal.science/search/index/?q=*&authIdPerson_i=1215683
        # - name: arXiv
        #   url: https://arxiv.org/search/?query=Dylan+Laplace+Mermoud&searchtype=all&source=header
        # - name: orcid
        #  url: https://orcid.org/0000-0002-1508-9656
        # - name: CV
        #   url: cv.pdf
        # - name: Location
        #   url: location/
        # - name: Office Hours
        #   url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=q-OuuE4AAAAJ&hl=fr
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat
        # - name: GitLab
        #  url: https://gitlab.com/DylanLaplaceMermoud
        - name: GitHub
          url: https://github.com/sihao-li
        # - name: Substack
        #   url: https://pmichaillat.substack.com
        - name: Twitter
          url: https://x.com/SihaoLS
        - name: Email
          url: mailto:si.li@ip-paris.fr

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
        favicon: "/favicon.ico"
        favicon16x16: "/favicon-16x16.png"
        favicon32x32: "/favicon-32x32.png"
        apple_touch_icon: "/apple-touch-icon.png"
        mask_icon: "/safari-pinned-tab.svg"
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Si Hao Li"
      icon: logo2.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
